### ISSUE TITLE
[Bug] 404 Not Found

### ISSUE THREAD

**Issue by Pheggas** [SpiReCZ/ulozto-streamer#1]
Hey, i just deployed this project on my homeserver via docker / docker compose / portainer. However i'm getting this error

Logs:
```
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     192.168.1.11:64871 - "GET / HTTP/1.1" 404 Not Found
INFO:     192.168.1.11:64871 - "GET /favicon.ico HTTP/1.1" 404 Not Found
```

and from browser i get simple `{"detail":"Not Found"}`. Any thoughts on this?

**Comment by MilosHavranek** [comment]
Hi, are you using the ulozto-streamer along with [ulozto-synology](https://github.com/SpiReCZ/ulozto-synology) ?
This project is creating a streaming handler for ulozto in a form of microservice, it does not have a frontend (web page) to access, it only provides REST APIs as a backend service.
For example Download Station for Synology acts as a frontend. User adds download to Download Station and it will work together once you install plugin for it. 
Added value for this solution is you can have all downloads handled at one place figuratively and it does not require development of another UI.
If you were to use something else like QNAP or self-hosted downloader (JDownloader, pyLoad) you would need to create plugin/addon to support the integration.

**Comment by Pheggas** [comment]
Ah, right. Sadly i don't have synology NAS. Thank you for providing info!
